# Generated by Django 4.1.7 on 2023-03-05 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0004_alter_tierimage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierimage',
            name='duration',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(300000)]),
        ),
    ]
