# Generated by Django 4.1.7 on 2023-03-10 14:29

from django.db import migrations, models
import images_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0005_alter_tierimage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_height_sizes',
            field=models.CharField(help_text='Comma-separated list of thumbnail height sizes (e.g. 200, 400)', max_length=255, validators=[images_api.models.validate_thumbnail_height_sizes]),
        ),
    ]
